relativeURLs = true
googleAnalytics = "UA-159072578-1"
title = "Hui Li"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Hui Li"
homepage = "https://huili.netlify.app/"

[params]
institution = "Economics and Management School, Wuhan University"
shortbio = "Assistant Professor"
logo = ""
Twitter = "Hui_Li_RUC"
Email = "lihui_econo@163.com"

[markup]
  [markup.highlight]
    style = "solarized-light"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
